### ISSUE TITLE
Organization related API

### ISSUE THREAD

**Issue by shunjikonishi** [code-check/github-api-scala#11]
## models
- [x] Organization
- [x] OrganizationInput
## operations
- [x] listOwnOrganizations
- [x] listUserOrganizations
- [x] getOrganization
- [x] UpdateOrganization(org: String, input: OrganizationInput)
## test
- [x] listOwnOrganizations
- [x] listUserOrganizations
- [x] getOrganization
- [x] UpdateOrganization(org: String, input: OrganizationInput)

**Comment by fanwashere** [comment]
@shunjikonishi review me.

**Comment by fanwashere** [comment]
This issue should be resolved. Should I close it?
