### ISSUE TITLE
Rewrite tests

### ISSUE THREAD

**Issue by shunjikonishi** [code-check/github-api-scala#21]
Currently we use code-check organization for test.
But some members doesn't have admin permission for this organization.
So, we have to change organization.

We'll use this organization.

https://github.com/orgs/celestialbeings
### GOAL
- All members can pass 'sbt test'

@fanwashere 
Try to run 'sbt test'.
Probably you will get some errors.
So, rewrite tests to be all green.

I guess what you should do are
- Make a repository for test
- Mod test/Constants.scala

**Comment by fanwashere** [comment]
## ToDo
- [x] IssueOpSpec
- [x] LabelOpSpec
- [x] MilestoneOpSpec
- [x] OrganizationOpSpec
- [x] RepositoryOpSpec
- [x] RepositoryAPISpec

## Maybe
- [x] Random value generator
