### ISSUE TITLE
Collaborator related APIs

### ISSUE THREAD

**Issue by shunjikonishi** [code-check/github-api-scala#5]
## models
- [x] Collabolator
  If the fields of Collaborator are same as User, it is not necessary.
## operations
- [x] listCollaborators
- [x] isCollaborator(owner: String, repo: String, username: String)
- [x] addCollaborator(owner: String, repo: String, username: String)
- [x] removeCollaborator(owner: String, repo: String, username: String)
## test
- [x] listCollaborators
- [x] isCollaborator(owner: String, repo: String, username: String)
- [x] addCollaborator(owner: String, repo: String, username: String)
- [x] removeCollaborator(owner: String, repo: String, username: String)

**Comment by sukeshni** [comment]
@shunjikonishi Please review 
https://github.com/code-check/github-api-scala/commit/bb47768a5d353abca3c9fa889aafc96c6eb296b2

**Comment by sukeshni** [comment]
@shunjikonishi 
Have to another test, will fix it.

**Comment by sukeshni** [comment]
@shunjikonishi Please review
https://github.com/code-check/github-api-scala/commit/730ecb3e66bc9f9535418ba2350aae841efddaa2

**Comment by shunjikonishi** [comment]
@sukeshni This is a issue, not pullrequest.
If you want me to code review, please write it in pullrequest. ( #27 )
