### ISSUE TITLE
User related API

### ISSUE THREAD

**Issue by shunjikonishi** [code-check/github-api-scala#9]
## models
- [x] User
- [x] UserInput
## operations
- [x] getAuthenticatedUser
- [x] getUser
- [x] updateAuthenticatedUser
- [x] getAllUsers
## test
- [x] getAuthenticatedUser
- [x] getUser
- [x] updateAuthenticatedUser
- [x] getAllUsers

**Comment by sukeshni** [comment]
@shunjikonishi review me
